version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  elasticsearch:
    image: "elasticsearch:7.17.2"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: "kibana:7.17.2"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
